version: '3.0'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '80:80'
    depends_on:
      - backend
      - frontend
  postgres: 
    image: 'postgres:15-bullseye'
    volumes:
      - ./data:/var/lib/pgsql/15/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  redis: 
    image: 'redis:6-alpine'
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGPASSWORD=mysecretpassword
      - PGUSER=postgres
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    
    

    
